name: lint shell scripts

on: [pull_request, push]

jobs:
  test:
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: fearphage/shellcheck-action@master
        env:
          DEBUG_ACTION: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
