name: lint shell scripts

on: [pull_request, push]

jobs:
  test:
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fearphage/shellcheck-action@allow-user-input
        env:
          DEBUG_ACTION: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          ignore-paths: not-here
