name: lint shell scripts

on: [pull_request, push]

jobs:
  test:
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fearphage/shellcheck-action@allow-user-input
        id: meh
        env:
          DEBUG_ACTION: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          dry-run: true
          ignore-paths: not-here
          include-files: >-
            README.md
            text-files/no-shebang
      - run:
        echo "files: ${{ steps.meh.outputs.files }}'

